### ISSUE TITLE
 psalm_clan.__init__() missing 2 required positional arguments: 'input_dim' and 'output_dim'

### ISSUE THREAD

**Issue by nongbaoting** [Protein-Sequence-Annotation/PSALM#2]
```
Traceback (most recent call last):
  File "/disk1/user/nong/source/Protein/annotate/PSALM.py", line 36, in <module>
    fire.Fire(Main)
  File "/disk1/user/nong/miniconda3/envs/PSALM/lib/python3.10/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/disk1/user/nong/miniconda3/envs/PSALM/lib/python3.10/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/disk1/user/nong/miniconda3/envs/PSALM/lib/python3.10/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/disk1/user/nong/source/Protein/annotate/PSALM.py", line 19, in annotate
    PSALM = psalm(clan_model_name="ProteinSequenceAnnotation/PSALM-1-clan",
  File "/disk1/user/nong/miniconda3/envs/PSALM/lib/python3.10/site-packages/psalm/psalm.py", line 195, in __init__
    self.clan_model = psalm_clan.from_pretrained(clan_model_name)
  File "/disk1/user/nong/miniconda3/envs/PSALM/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/disk1/user/nong/miniconda3/envs/PSALM/lib/python3.10/site-packages/huggingface_hub/hub_mixin.py", line 569, in from_pretrained
    instance = cls._from_pretrained(
  File "/disk1/user/nong/miniconda3/envs/PSALM/lib/python3.10/site-packages/huggingface_hub/hub_mixin.py", line 789, in _from_pretrained
    model = cls(**model_kwargs)
TypeError: psalm_clan.__init__() missing 2 required positional arguments: 'input_dim' and 'output_dim'

```

**Comment by ArpanSarkar** [comment]
Hi! Would you be able to provide a little more context (maybe a code snippet)? The `psalm_clan` class inherits from the HuggingFace `PyTorchModelHubMixin` class, which has the `from_pretrained` method. That allows us to get the PSALM clan weights + other configs like `input_dim` and `output_dim` from the [HF model hub](https://huggingface.co/ProteinSequenceAnnotation/PSALM-1-clan/tree/main). It looks like maybe the `config.json` file is not being recognized for some reason.

**Comment by nongbaoting** [comment]
sorry for missing the explanation. I follow the **Usage** as your provided and running the code as below , but error comes out 
```
import os, sys, re, gzip
from pathlib import Path
sys.path.append('/disk1/user/nong/source/commonFunctions')
import commonFunctions
import torch
from psalm import psalm

class Main:
    def annotate(self, ):
        # Load PSALM clan and fam models
        PSALM = psalm(clan_model_name="ProteinSequenceAnnotation/PSALM-1-clan",
                    fam_model_name="ProteinSequenceAnnotation/PSALM-1-family",
                    device = 'cuda') #cpu by default, replace with 'cuda' or 'mps' as needed

        # Prepare data (use PSALM.read_fasta(fasta_file_path) to get data directly from a FASTA file)
        data = [
            ("Human Beta Globin", "MVHLTPEEKSAVTALWGKVNVDEVGGEALGRLLVVYPWTQRFFESFGDLSTPDAVMGNPKVKAHGKKVLGAFSDGLAHLDNLKGTFATLSELHCDKLHVDPENFRLLGNVLVCVLAHHFGKEFTPPVQAAYQKVVAGVANALAHKYH"),
            ("Flavohemoprotein", "MLDAQTIATVKATIPLLVETGPKLTAHFYDRMFTHNPELKEIFNMSNQRNGDQREALFNAIAAYASNIENLPALLPAVEKIAQKHTSFQIKPEQYNIVGEHLLATLDEMFSPGQEVLDAWGKAYGVLANVFINREAEIYNENASKAGGWEGTRDFRIVAKTPRSALITSFELEPVDGGAVAEYRPGQYLGVWLKPEGFPHQEIRQYSLTRKPDGKGYRIAVKREEGGQVSNWLHNHANVGDVVKLVAPAGDFFMAVADDTPVTLISAGVGQTPMLAMLDTLAKAGHTAQVNWFHAAENGDVHAFADEVKELGQSLPRFTAHTWYRQPSEADRAKGQFDSEGLMDLSKLEGAFSDPTMQFYLCGPVGFMQFTAKQLVDLGVKQENIHYECFGPHKVL")
        ]

        # Visualize PSALM annotations (add optional save_path argument: PSALM.annotate(data,save_path="save_folder")
        PSALM.annotate(data)
        

if __name__ == '__main__':
    import fire
    print('Beginnng...')
    fire.Fire(Main)
```

**Comment by ArpanSarkar** [comment]
I just tested it again on my end, and I'm not getting this error. Which version of the package are you using? It should just pull the config and weights from the PSALM HuggingFace model hub. If it doesn't work still, you can try a manual workaround by importing `psalm_clan` and `psalm_fam` individually from `psalm`:
1. Initialize both the clan and fam models (i.e. specifying `input_dim` and `output_dim`). These will be specified in the `config.json` files for [fam](https://huggingface.co/ProteinSequenceAnnotation/PSALM-1-family/blob/main/config.json) and [clan](https://huggingface.co/ProteinSequenceAnnotation/PSALM-1-clan/blob/main/config.json)
2. Download the weights for each model ([fam ](https://huggingface.co/ProteinSequenceAnnotation/PSALM-1-family/blob/main/model.safetensors)and [clan](https://huggingface.co/ProteinSequenceAnnotation/PSALM-1-clan/blob/main/model.safetensors)) from the HF model hub. For fam, you will also need the [`maps.pkl` file](https://huggingface.co/ProteinSequenceAnnotation/PSALM-1-family/blob/main/maps.pkl) that contains all of the relevant mappings between fam and clan as well as their respective indices for parsing the output of the models.
3. Load the weights into the model ([guide](https://pytorch.org/tutorials/beginner/basics/saveloadrun_tutorial.html#:~:text=To%20load%20model%20weights%2C%20you,those%20necessary%20for%20loading%20weights.))
